[package]
name = "sample_api"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
axum = {version = "0.7.9"}
tokio = {version = "0.3.7", features = ["full"]}